receiver_email: "email@gmail.com" # email to send to
sender_email: "email@gmail.com" # email to send from 
smtp_server: "smtp.something.com"
smtp_port: 123
password: "**** **** **** ****" # The app-password of the sender_email email
city: "Z체rich" # Choose between Z체rich and Winterthur (Winterthur includes W채denswil listings)
url_woko: "https://www.woko.ch/en/nachmieter-gesucht"  # Long-term listings
#url_woko: "https://www.woko.ch/en/untermieter-gesucht"  # Short-term listings (sublets)
#url_woko: "https://www.woko.ch/en/zimmer-in-zuerich"  # Both listing types for Zurich (overrides the city parameter)
#url_woko: "https://www.woko.ch/en/zimmer-in-winterthur-und-waedenswil"  # Both listing types for Winterthur and W채denswil (overrides the city parameter)
timer: 120 # in s./ interval to update request
test_email: True
